apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
#- ../../../../jupyter/jupyter-web-app/base_v3
- ../../../../../apps/jupyter/jupyter-web-app/upstream/base
- ose-oauth-proxy
patchesStrategicMerge:
- addnoauthflags.yaml
#No need to build new image, added flags to deployment
#images:
#- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
#  newTag: v2.0.0
#  newName: quay.io/kubeflow/jupyter-web-app

patchesJson6902:
- target:
    kind: ServiceAccount
    version: v1
    name: service-account
  path: service-account.yaml
- target:
    kind: Service
    version: v1
    name: service
  path: service.yaml
